# Generated by Django 5.1.5 on 2025-01-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('remember_me', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
