# Generated by Django 5.1.5 on 2025-01-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_user_alter_building_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='building',
            name='east_wing_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='east_wing_length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='main_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='main_length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='total_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='total_length',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='total_width',
            field=models.FloatField(default=0.0),
        ),
    ]
