# Generated by Django 5.1.5 on 2025-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_building_building_type_building_east_wing_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='number_of_lightning_rods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='protection_radius',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='building',
            name='thunder_days_per_year',
            field=models.CharField(default='0-0', max_length=20),
        ),
    ]
