# Generated by Django 5.1.5 on 2025-02-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_building_number_of_lightning_rods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='east_wing_height',
        ),
        migrations.RemoveField(
            model_name='building',
            name='east_wing_length',
        ),
        migrations.RemoveField(
            model_name='building',
            name='height',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
        migrations.RemoveField(
            model_name='building',
            name='number_of_lightning_rods',
        ),
        migrations.RemoveField(
            model_name='building',
            name='protection_radius',
        ),
        migrations.RemoveField(
            model_name='building',
            name='thunder_days_per_year',
        ),
        migrations.AddField(
            model_name='building',
            name='eastwing_height',
            field=models.FloatField(default=0.0, verbose_name='Eastwing Building Height (m)'),
        ),
        migrations.AddField(
            model_name='building',
            name='eastwing_length',
            field=models.FloatField(default=0.0, verbose_name='Eastwing Building Length (m)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('education', 'Bangunan Pendidikan'), ('public', 'Bangunan Publik'), ('commercial', 'Bangunan Komersial'), ('hospital', 'Rumah Sakit'), ('religious', 'Bangunan Keagamaan')], max_length=20, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.CharField(choices=[('jakarta', 'DKI Jakarta'), ('jabar', 'Jawa Barat'), ('jatim', 'Jawa Timur'), ('sumut', 'Sumatera Utara'), ('sulsel', 'Sulawesi Selatan')], max_length=20, verbose_name='Building Location'),
        ),
        migrations.AlterField(
            model_name='building',
            name='main_height',
            field=models.FloatField(default=0.0, verbose_name='Main Building Height (m)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='main_length',
            field=models.FloatField(default=0.0, verbose_name='Main Building Length (m)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_height',
            field=models.FloatField(default=0.0, verbose_name='Total Building Height (m)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_length',
            field=models.FloatField(default=0.0, verbose_name='Total Building Length (m)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_width',
            field=models.FloatField(default=0.0, verbose_name='Total Building Width (m)'),
        ),
    ]
