# Generated by Django 5.1.5 on 2025-02-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_remove_building_east_wing_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='number_of_lightning_rods',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='protection_radius',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
