# Generated by Django 5.1.5 on 2025-02-05 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_building_number_of_lightning_rods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningRod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('distance', models.FloatField()),
                ('protection_level', models.FloatField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightning_rods', to='building.building')),
            ],
        ),
    ]
