# Generated by Django 5.1.5 on 2025-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_lightningrod'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='position_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='position_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='protection_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
