# Generated by Django 5.1.5 on 2025-02-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_building_distance_building_position_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('education', 'Bangunan Pendidikan'), ('public', 'Bangunan Publik'), ('commercial', 'Bangunan Komersial'), ('hospital', 'Rumah Sakit'), ('religious', 'Bangunan Keagamaan'), ('industrial', 'Bangunan Industri')], max_length=20, verbose_name='Building Type'),
        ),
    ]
