# Generated by Django 5.1.5 on 2025-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_alter_building_building_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
