# Generated by Django 5.1.5 on 2025-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0014_alter_project_status_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='min_strike_current',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Lightning Strike Current (kA)'),
        ),
        migrations.AddField(
            model_name='building',
            name='protection_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='Lightning Protection Efficiency (E)'),
        ),
        migrations.AddField(
            model_name='building',
            name='strike_current',
            field=models.FloatField(blank=True, null=True, verbose_name='Lightning Strike Current (kA)'),
        ),
        migrations.AddField(
            model_name='building',
            name='strike_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Lightning Strike Distance (m)'),
        ),
    ]
