# Generated by Django 5.1.5 on 2025-05-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0016_alter_building_min_strike_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='min_strike_current',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='protection_efficiency',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='strike_current',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='strike_distance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
