# Generated by Django 5.1.5 on 2025-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0017_alter_building_min_strike_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='min_strike_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='protection_efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='strike_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='strike_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
