# Generated by Django 5.1.5 on 2025-05-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0018_alter_building_min_strike_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.CharField(choices=[('jakarta', 'DKI Jakarta'), ('jabar', 'Jawa Barat'), ('jatim', 'Jawa Timur'), ('sumut', 'Sumatera Utara'), ('sulsel', 'Sulawesi Selatan'), ('batam', 'Batam')], max_length=20, verbose_name='Building Location'),
        ),
    ]
